### ISSUE TITLE
Unified deployment 

### ISSUE THREAD

**Issue by roll** [opentrials/opentrials#31]
We use different environment variables across the whole project. It's used by apps (via `.env` files), set on Travis CI/CD, sometimes exported (`set -a; source .env`) to dev env for `docker-compose`.

I suppose the good practice will be to have some naming conventions like:
- to have `OPENTRIALS_` prefix to avoid naming collision with other projects because of the exporting for the `docker-compose` (Heroku dictates to have `HOST` but docker-cloud doesn't have this problem).
- use additional semantic parts like `OPENTRIALS_DATABASE_` to describe variable scope.

The main target is to have env variables ready to live in any namespace without collision. Like `OPENTRIALS_DATABASE_URL_STAGING` will be unique.

For example `scraper` and `warehouse` use for now:

```
OPENTRIALS_WAREHOUSE_URL
OPENTRIALS_DATABASE_URL
OPENTRIALS_ICTRP_USER
OPENTRIALS_ICTRP_PASS
```

**Comment by roll** [comment]
cc @vitorbaptista @pwalsh

**Comment by vitorbaptista** [comment]
Considering that the deployments are isolated inside Docker or Heroku, do we need to add a `OPENTRIALS_` prefix? I mean, there won't be another app running in that environment, so we should never have name collisions (if we do, there's a bug somewhere).

Also, we shouldn't add the current environment name to the env name as in `OPENTRIALS_DATABASE_URL_STAGING`, but have one canonical like `OPENTRIALS_DATABASE_URL`.

**Comment by pwalsh** [comment]
@vitorbaptista several containers can be running on one host/cluster. the env vars are true across the host/cluster on Docker Cloud (hope I'm not mistaken there). So, we *may* need that. @roll can you confirm?

**Comment by roll** [comment]
The main reason we need this because `docker-compose` doesn't properly support `.env` files. So for run `docker-compose` locally developer should export environment variables to the local bash process (here will be collisions with other projects). 

For production it's fine to do not have prefix ibut for dev is highly recommended. Also for me it's just a good practice to start with prefixes to do not change everything after we will run into some new uses cases where prefixes are required.

**Comment by roll** [comment]
> Also, we shouldn't add the current environment name to the env name as in OPENTRIALS_DATABASE_URL_STAGING, but have one canonical like OPENTRIALS_DATABASE_URL.

With docker-cloud workflow I suppose we should because all our environment variables will be stored here - https://travis-ci.org/opentrials/api/settings - nothing else will go to app containers. So it looks like to support staging env we need to pass variables with env modifier and manage it on app level like:

```
# settings
if production
     use production env var
```
```

**Comment by vitorbaptista** [comment]
I have no experience with docker-compose, just starting to see how things fit together with Tutum, but they do seem to support .env files (as per https://docs.docker.com/compose/compose-file/). Also, the environment variables shouldn't be "global", but only applied to the server process. There's no harm in using the prefixes, though, so I'm happy to add them.

> With docker-cloud workflow I suppose we should because all our environment variables will be stored here - https://travis-ci.org/opentrials/api/settings - nothing else will go to app containers. So it looks like to support staging env we need to pass variables with env modifier and manage it on app level like:
>
> ```
> # settings
> if production
>      use production env var
> ```

The plan is to automatically deploy to both staging and production with Travis? I'd be a bit worried in that case, as I don't think our test suite is up to that level. It would need, for example, some end-to-end tests. What I usually have seen from my experience with Continuous Deployment was to deploy automatically to a staging site only. If staging seems good, it can then be promoted to production manually (as in clicking a button).

Also, from the 12 Factor App page about configs (http://12factor.net/config):
> Another aspect of config management is grouping. Sometimes apps batch config into named groups (often called “environments”) named after specific deploys, such as the `development`, `test`, and `production` environments in Rails. This method does not scale cleanly: as more deploys of the app are created, new environment names are necessary, such as `staging` or `qa`. As the project grows further, developers may add their own special environments like `joes-staging`, resulting in a combinatorial explosion of config which makes managing deploys of the app very brittle.
>
> In a twelve-factor app, env vars are granular controls, each fully orthogonal to other env vars. They are never grouped together as “environments”, but instead are independently managed for each deploy. This is a model that scales up smoothly as the app naturally expands into more deploys over its lifetime.

We sometimes need to check the current environment (for example, to disable debugging when in production), but these checks are minimal and can use the `ENV` variable. For things like database, etc., we'd better have a single variable name and change it as needed.

Couldn't these ENV variables live in Tutum cloud instead of Travis? This way Travis will only be responsible of deploying to Tutum, but after that all configuration takes place over there.

**Comment by roll** [comment]
@vitorbaptista Yes of course it will be `ENV` var:

> stacks/api.yml
```
server:
  image: opentrialsrobot/api
  restart: always
  command: ENV=PRODUCTION node --use_strict server.js
  environment:
    OPENTRIALS_DATABASE_URL:
    OPENTRIALS_SEARCHENGINE_URL:
```

> # stacks/api.yml
```
server:
  image: opentrialsrobot/api
  restart: always
  command: ENV=STAGING node --use_strict server.js
  environment:
    OPENTRIALS_DATABASE_URL:
    OPENTRIALS_SEARCHENGINE_URL:
```

Problem here is docker-cloud don't have env vars settings section (because of containers nature) like heroku so all information should be passed while Travis deploy. We have only one travis project for repository - is means we have to pass sensitive data with environment markers.

About deployment for now it deploys only on commits with `[delpoy]` mark in commit message. With different envs we could have `[staging]` and `[production]` marks. And even this is not a real deployment - we still need to push the `redeploy` button on Tutum.

**Comment by roll** [comment]
Sorry second listing was for `stacks/api--staging.yml` (fixed).

**Comment by pwalsh** [comment]
@roll you can set env vars in the Docker Cloud UI, just like with Heroku, so there is no need to hard code values in codebase, as far as I see.

**Comment by roll** [comment]
@pwalsh how? only in stack definitions AFAIK - I've setup travis to do it automatically. 

It's not about hard-coding in codebase of course (it's our credentials=). Everything live here - https://travis-ci.org/opentrials/processors/settings - creating stacks with this values.

**Comment by pwalsh** [comment]
yes, you are right, only as part of a stack definition.

**Comment by roll** [comment]
High-level:

- stack files in codebase (in `stacks` dir) like templates for tutum without env vars (also it's for local `docker-compose` runs)
- env vars in travis settings
- travis renders stack files with env vars and push to tutum

With this approach we only have one place to store all our env vars - travis settings. So don't have a place to have env for staging. So it should store both stage/prod cred suffixed as I see for now.

But it's only a detail of deployment technique - after all we still have `12 Factor App` compatible way.

**Comment by roll** [comment]
Morning) As I said we was discussing just a details. So I've figured out how to add some details to make it fully `12 Factor App` like:

1. In `stacks` directory we having stacks **without** environment modifiers like:

> stacks/api.yml
```yml
server:
  image: opentrialsrobot/api
  restart: always
  command: node --use_strict server.js
  # no values means read from environment on docker-compose or docker-cloud call
  environment:
    ENV: # prefix?
    OPENTRIALS_DATABASE_URL:
    OPENTRIALS_SEARCHENGINE_URL:
```

2. At travis we have all creadentials set to secure env vats in settings:

> https://travis-ci.org/opentrials/processors/settings
```bash
OPENTRIALS_DATABASE_URL=***
OPENTRIALS_DATABASE_URL__STAGING=***
OPENTRIALS_SEARCHENGINE_URL=***
OPENTRIALS_SEARCHENGINE_URL__STAGING=***
```

3. In travis file we have deployment router based on commit message (could be rebased on tags or branches - any method we will prefer)

> .travis.yml
```yml
deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      condition: '`git show -s --format=%B ${TRAVIS_COMMIT} | grep "\[production\]"`'
  - provider: script
    script: bash scripts/deploy--staging.sh
    on:
      condition: '`git show -s --format=%B ${TRAVIS_COMMIT} | grep "\[staging\]"`'
```

4. In `scripts` folder we have this deployment scripts with env modifiers:

> scripts/deploy.sh

```
ENV=PRODUCTION
# put api to `api` stack on tutum
```

> scripts/deploy--staging.sh

```
ENV=PRODUCTION
OPENTRIALS_DATABASE_URL=OPENTRIALS_DATABASE_URL__STAGING
OPENTRIALS_SEARCHENGINE_URL=OPENTRIALS_SEARCHENGINE_URL__STAGING
# put api to `api--staging` stack on tutum
```

So voila it's full analogy with heroku approach.

About env vars prefixing - really don't now. It's just developer machine potential collisions problem. If we (developers) could live with it - we don't need prefixes.
